name: ecp
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.1
  json_annotation: ^4.9.0
  libsignal_protocol_dart: ^0.7.4
  uuid: ^4.5.2

dev_dependencies:
  test: ^1.24.9
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
