name: ecp
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.2.1
  libsignal_protocol_dart: ^0.7.4

dev_dependencies:
  test: ^1.24.9
